@startditaa
模块结构图

        /--------------\
        |cBLU Browser  |
        |--------------|    JSONRPC over WebSocket
        | WebSocket    |--------------------------------\
        \--------------/                                |
                                                        |
                                                        |
/-+-----------------------+-\                           |
| |         GUI           | |                           |
| \-----------------------/ |                           |
|                           |                           |
|          /----------------+                           |
|          |c1AB            |                           |
|          |Local WebServer |<--------------------------/
|          \----------------+
| cGRE                      |
|            /--------------+    /----------------------\
| Agent      | c1FF         +--->|cPNK SIP Registrar #1 |
| Executable |   SIP UAC    |    +----------------------+
|            |              +--->|cPNK SIP Registrar #2 |
|            \--------------+    \----------------------/
|                           |
|            /--------------+    /----------------------\
|            | cYEL         +--->|cPNK CTI Server #1    |
|            |  CTI Client  |    +----------------------+
|            |              +--->|cPNK CTI Server #2    |
|            \--------------+    \----------------------/
|                           |
\---------------------------/

@endditaa
