site_name: IPSC 座席客户端开发人员指南
site_author: 刘雪彦
copyright: 广州市和声信息技术有限公司 © 2021

docs_dir: src
use_directory_urls: false

nav:
  - index.md

  - docs/install.md
  - docs/config.md
  - docs/startup.md

  - API 参考:
    - JSONRPC over WebSocket:
      - docs/api/jsonrpc_websocket/jsonrpc.md
      - docs/api/jsonrpc_websocket/mixed_content.md

    - 类型:
        - docs/api/types/class_overview.md
        - docs/api/types/agent.md
        - docs/api/types/cti_server.md
        - docs/api/types/group.md
        - docs/api/types/call.md
        - docs/api/types/queue_info.md
        - docs/api/types/sip_account.md
        - docs/api/types/sip_call.md
        - docs/api/types/enums.md

    - 方法:
        - docs/api/methods/cti_server.md
        - docs/api/methods/group.md
        - docs/api/methods/status.md
        - docs/api/methods/sip.md
        - docs/api/methods/dial.md
        - docs/api/methods/call.md
        - docs/api/methods/queue.md
        - docs/api/methods/manage.md
        - docs/api/methods/gui.md
    - 事件: []
    #       - docs/api/events/client_connection_state_changed.md
    #       - docs/api/events/agent_status_changed.md
    #       - docs/api/events/sip_register_state_changed.md
    #       - docs/api/events/ring_received.md
    #       - docs/api/events/skill_groups_changed.md
    #       - docs/api/events/hold_list_changed.md

plugins:
  - search
  - with-pdf:
      enabled_if_env: ENABLE_PDF_EXPORT
      toc_title: 目录
      toc_level: 3
      cover_title: "IPSC 座席客户端"
      cover_subtitle: "开发人员指南"

theme:
  name: material
  language: zh
  font: false

  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections: false

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: 切换到暗色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/lightbulb
        name: 切换到亮色模式

markdown_extensions:
  - pymdownx.extra
  ### pymdownx.extra replaces markdown.extensions.extra, Here is the full list of included extensions:
  ## pymdownx.betterem
  ## pymdownx.superfences
  ## markdown.extensions.footnotes
  ## markdown.extensions.attr_list
  ## markdown.extensions.def_list
  ## markdown.extensions.tables
  ## markdown.extensions.abbr
  ## markdown.extensions.md_in_html
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.critic:
      mode: view
  - pymdownx.snippets
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  # Officially Supported Extensions
  - admonition
  - meta
  # - sane_lists:
  # - smarty:
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  # 3rd extensions
  - plantuml_markdown:
      # server: http://www.plantuml.com/plantuml
      format: svg
